### ISSUE TITLE
Question: Why do you need both the files and the src options?

### ISSUE THREAD

**Issue by sabhiram** [christill/grunt-sanitize#1]
Don't you think it would be enough to just have one of these?

**Comment by justnom** [comment]
There are many ways to define files in Grunt. Using a `files` array of objects with a `src` property - is just one of them.

More info in the Grunt docs here: http://gruntjs.com/configuring-tasks#files

**Comment by sabhiram** [comment]
I just mean that in this context, is there ever a time where you can have a sibling to the "src" attribute under "files"?

**Comment by justnom** [comment]
No there isn't - your correct about that. Using the `src`/`dest` format is just standard behaviour in Grunt. 

When registering a task - it allows you to use `this.files` to iterate over the files - no matter how the user defined their files.

**Comment by sabhiram** [comment]
Oh I see, sorry didnt realize that grunt will process that for you. Was just looking at this repo since it was posted on reddit asking for contributors :)
